<Search>
    f_product: product
    StackLayout:
        orientation: 'lr-tb'
        Label:
            text: 'Search'
            size_hint: (None, 0.07)
            width: 50
        TextInput:
            id: product
            multiline: False
            padding: (10, 10)
            width: 670
            size_hint: (None, 0.07)
            hint_text: 'Search for product'
        Button:
            text: 'Enter'
            size_hint: (None, 0.07)
            width: 70